title: "Daily AI Trend Reporter"
description: "Automatically updated daily AI research digest"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed

# RSS Feed configuration
feed:
  path: feed.xml
  limit: 10
  categories:
  - posts
